# Generated by Django 2.2.28 on 2024-11-17 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeroport',
            fields=[
                ('id_aeroport', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nom', models.CharField(default='Aéroport Par Défaut', max_length=100, unique=True)),
                ('capacite', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='aeroports/')),
            ],
        ),
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id_avion', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('compagnie_aerienne', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='avion/')),
                ('situation', models.CharField(choices=[('Ready', 'Prêt'), ('Maintenance', 'En maintenance'), ('In Flight', 'En vol')], default='Ready', max_length=20)),
                ('lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviation.Aeroport')),
            ],
        ),
    ]
